import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FaGoogle } from "react-icons/fa";

import { initializeApp } from "firebase/app";
import {
  getAuth,
  GoogleAuthProvider,
  signInWithPopup,
  signOut,
} from "firebase/auth";


import { useAuthState } from "react-firebase-hooks/auth";
// import { useCollectionData } from "react-firebase-hooks/firestore";
// import Navbar from "../components/Navbar"
// import Hero from "../components/Hero"

// import { Fragment } from "react";
// import { Disclosure, Menu, Transition } from "@headlessui/react";
// import { MenuIcon, XIcon } from "@heroicons/react/outline";

const firebaseConfig = {
  apiKey: "AIzaSyAmU2bGMHOrv4OPUphkjwJwKMKTXAReV-s",
  authDomain: "deca-dash.firebaseapp.com",
  projectId: "deca-dash",
  storageBucket: "deca-dash.appspot.com",
  messagingSenderId: "469040583347",
  appId: "1:469040583347:web:470294aa236fcd4957d6c6",
  measurementId: "G-WS8ZFNED11",
};


const app = initializeApp(firebaseConfig);
const auth = getAuth(app);

export default function Home() {
  const [user] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>Borrow - The College Sharing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? <Dashboard /> : <SignIn />}
    </div>
  );
}

function SignIn() {
  const signInWithGoogle = () => {
    const provider = new GoogleAuthProvider();
    signInWithPopup(auth, provider);
  };

  return (
    <div className="relative bg-white overflow-hidden h-screen	">
      <div className="max-w-7xl mx-auto">
        <div className="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-lg lg:w-full lg:pb-28 xl:pb-32">
          <main className="mt-10 mx-auto max-w-7xl lg:pt-40 px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
            <div className="sm:text-center lg:text-left">
              <h1 className="text-4xl tracking-tight font-extrabold text-blue-500 sm:text-5xl md:text-6xl">
                <span className="block xl:inline">Deca Dashboard</span>{" "}
              </h1>
              <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
                DECA Dashboard offers curated MCQs and case studies across all
                DECA clusters, providing a focused platform for students to hone
                their competitive edge and business acumen.
              </p>
              <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
                <div className="rounded-md mt-5 shadow">
                  <a
                    href="#"
                    onClick={signInWithGoogle}
                    className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-blue-500 bg-blue-100 hover:bg-blue-200 md:py-4 md:text-lg md:px-10"
                  >
                    <FaGoogle className="mr-2 " />
                    Sign in with Google
                  </a>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
      <div className="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
        <img
          className="h-full w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full"
          src="https://assets-global.website-files.com/635c470cc81318fc3e9c1e0e/6480c8e19218fd55a752cdd6_compete_hs_header.webp"
          alt=""
        />
      </div>
    </div>
  );
}

function SignOut() {

  return (
    <div>
      Welcome to Deca Dashboard
      <a
        href="#"
        className="block px-4 py-2 text-sm text-gray-700"
        onClick={() => signOut(auth)}
      >
        Sign out
      </a>
    </div>
  );
}

function Dashboard() {
  return (
    <div>
      <SignOut />
    </div>
  );
}
